In [1]:
import numpy as np
import pandas as pd

In [3]:
AIS = pd.read_csv('~/Downloads/AIS_2019_01_01.csv', delimiter=',')

In [5]:
AIS.head()

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TranscieverClass
0,338208626,2019-01-01T00:00:05,37.86505,-122.31405,0.0,-165.0,511.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,B
1,367420490,2019-01-01T00:00:04,31.26095,-91.65160,4.5,15.0,31.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,B
2,338060122,2019-01-01T00:00:04,30.67109,-81.46722,1.9,-67.4,511.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,B
3,368018190,2019-01-01T00:00:04,30.70736,-88.04332,0.0,-103.6,301.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,B
4,368039230,2019-01-01T00:00:04,35.08305,-90.14214,0.0,-182.3,4.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,B

In [6]:
AIS.tail()

,MMSI,BaseDateTime,LAT,LON,SOG,COG,Heading,VesselName,IMO,CallSign,VesselType,Status,Length,Width,Draft,Cargo,TranscieverClass
7509643,366996830,2019-01-01T23:59:59,38.40355,-82.55581,0.1,-147.3,511.0,ROAN,NaN,WDC2724,31.0,0.0,14.0,6.0,NaN,31.0,B
7509644,366947510,2019-01-01T23:59:59,36.84783,-89.14084,4.6,22.0,19.0,INEZ ANDREAS,NaN,WDB7752,31.0,12.0,56.0,15.0,NaN,NaN,B
7509645,372945000,2019-01-01T23:59:59,33.66295,-119.43170,8.3,92.0,90.0,ANDROMEDA SPIRIT,IMO9372327,3ELH2,70.0,0.0,180.0,30.0,9.2,70.0,B
7509646,367567220,2019-01-01T23:59:59,30.02144,-89.90802,0.0,-135.9,180.0,MAN O' WAR,NaN,WDG7432,31.0,0.0,23.0,9.0,NaN,NaN,B
7509647,367342960,2019-01-01T23:59:59,24.33402,-82.26947,14.7,-145.6,265.0,GOLDEN STATE,IMO9407562,WHDV,80.0,0.0,183.0,32.0,12.8,80.0,B

In [ ]:
AIS[AIS.MMSI==]