# Applying Functions
One of the key concepts in Pandas is that you can apply functions to the data frame itself. This differs from how data manipulation is done usually in Python, where loops and new data structures is primarily how you end up operating.

In [1]:
# Load your dataframe
import pandas as pd
csv_url = "https://raw.githubusercontent.com/paiml/wine-ratings/main/wine-ratings.csv"
df = pd.read_csv(csv_url, index_col=0)
df.head()

,name,grape,region,variety,rating,notes
0,1000 Stories Bourbon Barrel Aged Batch Blue Ca...,NaN,"Mendocino, California",Red Wine,91.0,"This is a very special, limited release of 100..."
1,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,89.0,The California Gold Rush was a period of coura...
2,1000 Stories Bourbon Barrel Aged Gold Rush Red...,NaN,California,Red Wine,90.0,The California Gold Rush was a period of coura...
3,1000 Stories Bourbon Barrel Aged Zinfandel 2013,NaN,"North Coast, California",Red Wine,91.0,"The wine has a deep, rich purple color. An int..."
4,1000 Stories Bourbon Barrel Aged Zinfandel 2014,NaN,California,Red Wine,90.0,Batch #004 is the first release of the 2014 vi...

We want to set the "top" wines given some arbitrary opinion on the rating. Wines are usually rated from 80 points to 100, and wines in the 90-94 point range are already good. So let's set the business requirement to set anything that is 95 points or greater to be "good".

In [3]:
# the function can be a regular function or a headless one with lambda

def good_wine(value):
    if value > 94:
        return True
    return False

df['good'] = df['rating'].apply(good_wine)
df.query('rating > 94').head()

,name,grape,region,variety,rating,notes,good
36,3 Rings Reserve Shiraz 2004,NaN,"Barossa Valley, Barossa, South Australia, Aust...",Red Wine,96.0,Vintage Comments : Classic Barossa vintage con...,True
110,Aalto 2005,NaN,"Ribera del Duero, Spain",Red Wine,95.0,The grapes come exclusively from old vineyards...,True
111,Aalto 2007,NaN,"Ribera del Duero, Spain",Red Wine,95.0,It is ironic that one of the youngest properti...,True
113,Aalto 2008,NaN,"Ribera del Duero, Spain",Red Wine,95.0,This wine's elegance and fruitful presence per...,True
121,Aalto 2016,NaN,"Ribera del Duero, Spain",Red Wine,95.0,"Deep purple red color, as corresponds to old T...",True